name: tf2
channels:
  - defaults
dependencies:  
  - pip:
    - matplotlib==3.3.3
    - numpy==1.18.5
    - opencv-python==4.4.0.46
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.1
    - tensorflow-addons==0.11.2
    - tensorflow-estimator==2.3.0
    - scikit-image==0.18.1
    - Pillow==8.1.0
    - ipython==7.19.0